### ISSUE TITLE
Convert to OpenMC boundary_type

### ISSUE THREAD

**Issue by zxkjack123** [makeclean/csg2csg#28]
I converted a model using `csg2csg` from MCNP to OpenMC. And met the following error:
```
ERROR: No boundary conditions were applied to any surfaces!
application called MPI_Abort(MPI_COMM_WORLD, -1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=-1
:
system msg for write_line failure : Bad file descriptor
Traceback (most recent call last):
  File "input.py", line 157, in <module>
    main(args.geom, args.nps, args.run, args.plot, args.vol)
  File "input.py", line 129, in main
    openmc.run()
  File "/home/zxk/opt/openmc/openmc/executor.py", line 212, in run
    _run(args, output, cwd)
  File "/home/zxk/opt/openmc/openmc/executor.py", line 30, in _run
    ''.join(lines))
subprocess.CalledProcessError: Command 'openmc' died with <Signals.SIGSEGV: 11>.
```

I think this error is related to the boundary type. In MCNP, we need to define the  entire universion, and set the graveyard using `imp:n=0`.

But in OpenMC, it seems that it uses `boundary_type='vacuum'` to define the boundary of the graveyard.

Therefore, when converts the input file from MCNP to OpenMC, we need to detect the boundary surface of the graveyard by `imp:n=0` or `imp:p=0`. And set these surface with type `vacuum`.

**Comment by makeclean** [comment]
Hmm it should do that if your cells use imp:n as opposed to a data block. Could you share your geometry?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by zxkjack123** [comment]
@makeclean Sorry for that, I just checked in the file, there isn't `imp:n`. It is the FNG model, I will send the file to you via slack.

**Comment by makeclean** [comment]
@zxkjack123 ah ok, no problem. I haven't implemented block reading for importances or weights yet, feel free to have a go though! I've not got huge amounts of time, and the 'perceived complexity' of the number of different options one has for defining importances has put this down my list, e.g. explicitly 1 2 3 4 5, repeated  1 4R, mulitiplicative 1 3.5M 3.5M, interpolative (sp?) 1 2I 4, im sure there are more :)
